CREATE DATABASE tstrading;
  -- [ [ WITH ] [ OWNER [=] user_name ]
  -- [ TEMPLATE [=] template ]
  -- [ ENCODING [=] encoding ]
  -- [ LC_COLLATE [=] lc_collate ]
  -- [ LC_CTYPE [=] lc_ctype ]
  -- [ TABLESPACE [=] tablespace_name ]
  -- [ ALLOW_CONNECTIONS [=] allowconn ]
  -- [ CONNECTION LIMIT [=] connlimit ]
  -- [ IS_TEMPLATE [=] istemplate ] ]